#!/usr/bin/env node
// Design phase only: render every screen state of the approved flow (docs/prototypes/flow.json) in the
// platform's final look — Material 3 on Android, the system look on iOS — with the theme that
// theme.mjs applied. Writes docs/prototypes/look/:
//
//   look/screens.html   every screen and state on one page, in flow order, per platform and theme
//   look/index.html     one screen: ?platform=<android|ios>&screen=<screen>&state=<state>&theme=<light|dark>
//
//   node screens.mjs [--spec docs/prototypes/flow.json] [--out <folder>] [--platform android|ios|both]
//
// --platform defaults to "platforms" in the spec; platforms already set up in look/ stay. Run it
// again whenever flow.json changes: everything in look/ is generated (an applied theme is kept).
// The screens are pictures of the look, not a working app: controls don't do anything.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { workspace } from './lib/workspace.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const kit = path.join(here, '..', 'assets', 'design-kit');
const args = process.argv.slice(2);
const opt = (n, d) => { const i = args.indexOf(`--${n}`); return i >= 0 ? args[i + 1] : d; };
const out = workspace(opt('out'));
const specFile = path.resolve(opt('spec', path.join(out, 'flow.json')));
const look = path.join(out, 'look');
const rel = (p) => { const r = path.relative(process.cwd(), p) || '.'; return r.startsWith('..') ? p : r; };
const die = (msg) => { console.error(`✗ ${msg}`); process.exit(1); };

if (!fs.existsSync(specFile)) die(`No spec at ${rel(specFile)}. The design phase starts from the approved flow.`);
let spec;
try { spec = JSON.parse(fs.readFileSync(specFile, 'utf8')); } catch (e) { die(`${rel(specFile)} is not valid JSON: ${e.message}`); }
const journeys = spec.journeys || [];
if (!journeys.some((j) => (j.screens || []).length)) die(`${rel(specFile)} has no screens.`);

const supported = fs.readdirSync(path.join(kit, 'tokens')).filter((f) => f.endsWith('.css')).map((f) => f.slice(0, -4));
const wanted = opt('platform') || (Array.isArray(spec.platforms) && spec.platforms.length ? spec.platforms.join(',') : '');
if (!wanted) die('Which platform? Pass --platform android|ios|both, or set "platforms" in the spec.');
const asked = wanted === 'both' ? ['android', 'ios'] : wanted.split(',').map((s) => s.trim()).filter(Boolean);
const existing = path.join(look, 'index.html');
const linked = fs.existsSync(existing) ? [...fs.readFileSync(existing, 'utf8').matchAll(/href="tokens\/([\w-]+)\.css" data-platform/g)].map((m) => m[1]) : [];
const platforms = [...new Set([...linked, ...asked])];
const unknown = platforms.filter((p) => !supported.includes(p));
if (unknown.length) die(`Unsupported platform: ${unknown.join(', ')}. Supported: ${supported.join(', ')}.`);

// ---------- the kit ----------
const vars = {
  '{{APP_NAME}}': spec.app || 'App',
  // A theme applied by theme.mjs (tokens/<p>.theme.css) stays linked when index.html is rewritten.
  '{{PLATFORM_STYLES}}': platforms.map((p) =>
    `  <link rel="stylesheet" href="tokens/${p}.css" data-platform="${p}">\n${fs.existsSync(path.join(look, 'tokens', `${p}.theme.css`)) ? `  <link rel="stylesheet" href="tokens/${p}.theme.css" data-platform="${p}" data-theme-link>\n` : ''}  <link rel="stylesheet" href="platform/${p}.css" data-platform="${p}">`).join('\n'),
  '{{PLATFORM_SCRIPTS}}': platforms.map((p) => `  <script src="platform/${p}.js"></script>`).join('\n'),
};
const copy = (src, dest) => {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  let text = fs.readFileSync(src, 'utf8');
  for (const [k, v] of Object.entries(vars)) text = text.replaceAll(k, v);
  fs.writeFileSync(dest, text);
};
for (const f of fs.readdirSync(kit)) if (!fs.statSync(path.join(kit, f)).isDirectory()) copy(path.join(kit, f), path.join(look, f));
for (const p of platforms) for (const f of [`tokens/${p}.css`, `platform/${p}.css`, `platform/${p}.js`]) copy(path.join(kit, f), path.join(look, f));

// The flow, numbered the same way as the sketch (S1, S2, … in file order).
let n = 0;
for (const j of journeys) for (const s of j.screens || []) s.sid = `S${++n}`;
fs.writeFileSync(path.join(look, 'flow-data.js'), `/* Generated by scripts/screens.mjs from ${path.basename(specFile)}. Don't edit: change the spec and run it again. */\nwindow.FLOW = ${JSON.stringify(spec, null, 2)};\n`);

// ---------- the overview page ----------
const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const SIZE = { android: [412, 915], ios: [393, 852] };
const designFile = path.join(out, 'notes', 'DESIGN.md');
const aaa = fs.existsSync(designFile) && /^\s*contrast:\s*high\b/m.test(fs.readFileSync(designFile, 'utf8'));
const sections = journeys.map((j) => `<section>
<h2>${esc(j.title || j.id)}</h2>
<div class="grid">
${(j.screens || []).map((s) => `<figure data-screen="${esc(s.screen)}" data-state="${esc(s.state)}">
  <div class="device"><iframe title="${esc(`${s.sid} ${s.title || s.screen}`)}" loading="lazy"></iframe></div>
  <figcaption><b>${esc(s.sid)}</b> · ${esc(s.title || `${s.screen} · ${s.state}`)} <span class="check" hidden></span><ul class="issues" hidden></ul></figcaption>
</figure>`).join('\n')}
</div>
</section>`).join('\n');

fs.writeFileSync(path.join(look, 'screens.html'), `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(spec.app || 'App')} — final-look screens</title>
<style>
  :root { color-scheme: light dark; --bg: #f7f7f8; --fg: #1b1b1f; --muted: #5f5f66; --card: #fff; --line: #e2e2e6; --bad: #b3261e; --ok: #1b6e3a; }
  @media (prefers-color-scheme: dark) { :root { --bg: #131316; --fg: #e5e5ea; --muted: #a0a0a8; --card: #1d1d21; --line: #2e2e33; --bad: #ffb4ab; --ok: #7fd99a; } }
  * { box-sizing: border-box; }
  body { margin: 0; font: 14px/1.45 system-ui, sans-serif; background: var(--bg); color: var(--fg); }
  header { position: sticky; top: 0; z-index: 1; background: var(--bg); border-bottom: 1px solid var(--line); padding: 12px 16px; display: flex; flex-wrap: wrap; gap: 10px 20px; align-items: center; }
  h1 { font-size: 16px; margin: 0 12px 0 0; }
  h2 { font-size: 13px; text-transform: uppercase; letter-spacing: .06em; color: var(--muted); margin: 24px 16px 8px; }
  select { font: inherit; padding: 4px 6px; }
  #summary { color: var(--muted); }
  .grid { display: flex; flex-wrap: wrap; gap: 20px; padding: 0 16px 16px; }
  figure { margin: 0; background: var(--card); border: 1px solid var(--line); border-radius: 12px; overflow: hidden; width: calc(var(--w) * var(--k) * 1px); }
  .device { width: calc(var(--w) * var(--k) * 1px); height: calc(var(--h) * var(--k) * 1px); overflow: hidden; }
  iframe { width: calc(var(--w) * 1px); height: calc(var(--h) * 1px); border: 0; transform: scale(var(--k)); transform-origin: 0 0; display: block; }
  figcaption { padding: 8px 10px; font-size: 12px; color: var(--muted); border-top: 1px solid var(--line); }
  figcaption b { color: var(--fg); }
  .check { float: right; font-weight: 600; }
  .check.ok { color: var(--ok); } .check.bad { color: var(--bad); cursor: pointer; text-decoration: underline; }
  .issues { margin: 6px 0 0; padding-left: 16px; color: var(--bad); overflow-wrap: anywhere; }
</style>
</head>
<body style="--w: 412; --h: 915; --k: .62">
<header>
  <h1>${esc(spec.app || 'App')} — final-look screens</h1>
  <label${platforms.length > 1 ? '' : ' hidden'}>Platform <select id="platform">${platforms.map((p) => `<option value="${p}">${p === 'ios' ? 'iOS' : 'Android'}</option>`).join('')}</select></label>
  <label>Theme <select id="theme"><option value="light">Light</option><option value="dark">Dark</option></select></label>
  <label>Text size <select id="scale"><option value="1">100%</option><option value="1.3">130%</option><option value="2">200%</option></select></label>
  <span id="summary"></span>
</header>
${sections}
<script>
  const SIZE = ${JSON.stringify(SIZE)};
  const MIN_CONTRAST = ${aaa ? 7 : 4.5};
  const $ = (id) => document.getElementById(id);
  const LABEL = { smallTargets: 'touch target too small', unnamedControls: 'control without a name', overflow: 'wider than the screen', clippedText: 'text cut off', overlapping: 'content overlapping', lowContrast: 'low contrast' };
  function summarise() {
    const figs = [...document.querySelectorAll('figure')];
    const done = figs.filter((f) => f.dataset.issues != null);
    const bad = done.filter((f) => f.dataset.issues !== '0');
    $('summary').textContent = done.length < figs.length ? 'Checking ' + done.length + ' of ' + figs.length + '…'
      : bad.length ? bad.length + ' of ' + figs.length + ' screens have something to look at (click the red note under a screen)' : figs.length + ' screens · checks passed (touch targets, overflow, contrast ' + MIN_CONTRAST + ':1)';
  }
  function check(fig, frame) {
    let r; try { r = frame.contentWindow.__prototypeAudit({ minContrast: MIN_CONTRAST }); } catch (e) { return; }
    const list = Object.keys(LABEL).flatMap((k) => (r[k] || []).map((x) => LABEL[k] + ': ' + x));
    const badge = fig.querySelector('.check'), ul = fig.querySelector('.issues');
    fig.dataset.issues = String(list.length);
    badge.hidden = false; badge.className = 'check ' + (list.length ? 'bad' : 'ok');
    badge.textContent = list.length ? list.length + (list.length === 1 ? ' issue' : ' issues') : '✓';
    ul.innerHTML = ''; ul.hidden = true;
    for (const t of list) { const li = document.createElement('li'); li.textContent = t; ul.append(li); }
    badge.onclick = () => { ul.hidden = !ul.hidden; };
    summarise();
  }
  function load() {
    const p = $('platform').value, [w, h] = SIZE[p] || SIZE.android;
    document.body.style.setProperty('--w', w); document.body.style.setProperty('--h', h);
    for (const fig of document.querySelectorAll('figure')) {
      const frame = fig.querySelector('iframe');
      delete fig.dataset.issues; fig.querySelector('.check').hidden = true; fig.querySelector('.issues').hidden = true;
      frame.onload = () => setTimeout(() => check(fig, frame), 900);
      frame.src = 'index.html?chrome=on&platform=' + p + '&theme=' + $('theme').value + '&fontScale=' + $('scale').value
        + '&screen=' + encodeURIComponent(fig.dataset.screen) + '&state=' + encodeURIComponent(fig.dataset.state);
    }
    summarise();
  }
  for (const id of ['platform', 'theme', 'scale']) $(id).addEventListener('change', load);
  load();
</script>
</body>
</html>
`);

console.log(`✓ ${rel(look)}: ${n} screen state(s) for ${platforms.join(', ')}`);
console.log(`  Look at them: node ${rel(path.join(here, 'serve.mjs'))} --dir ${rel(look)}   then open /screens.html`);
console.log(`  One screen:   index.html?platform=${platforms[0]}&screen=<screen>&state=<state>&theme=light|dark`);
